FROM node:lts-hydrogen

COPY ./build /peerprep_matching_service_mongo_init/
COPY package.json /peerprep_matching_service_mongo_init/

WORKDIR /peerprep_matching_service_mongo_init

RUN npm install --omit=dev -y

CMD node main.js
