apiVersion: v1
kind: Secret
metadata:
  name: matching-service-database-initialiser-secret
  namespace: peerprep
type: Opaque
data:
  mongo-admin-uri: # TODO: Set this (encode in base64)
  mongo-user-pass: # TODO: Set this (encode in base64)
