apiVersion: v1
kind: Service
metadata:
  name: matching-service-api-service
  namespace: peerprep
spec:
  selector:
    app: matching-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
